<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="WINDOWS-BR9DI0P" failures="3" tests="16" name="firefoxTest" time="108.713" errors="0" timestamp="2025-05-26T19:49:52 CDT">
  <testcase classname="testCases.TC01_LaunchApplication" name="testLaunchApplication" time="0.089"/>
  <testcase classname="testCases.TC03_AddToCart" name="testAddToCart" time="2.519">
    <skipped/>
  </testcase> <!-- testAddToCart -->
  <testcase classname="testCases.TC03_AddToCart" name="testAddToCart" time="0.203">
    <skipped/>
  </testcase> <!-- testAddToCart -->
  <testcase classname="testCases.TC03_AddToCart" name="testAddToCart" time="1.265">
    <failure type="java.lang.AssertionError" message="Test failed due to unexpected exception.">
      <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at testCases.TC03_AddToCart.testAddToCart(TC03_AddToCart.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testAddToCart -->
  <testcase classname="testCases.TC05_AddToWishList" name="testAddToWishList" time="12.52">
    <skipped/>
  </testcase> <!-- testAddToWishList -->
  <testcase classname="testCases.TC05_AddToWishList" name="testAddToWishList" time="10.335">
    <skipped/>
  </testcase> <!-- testAddToWishList -->
  <testcase classname="testCases.TC05_AddToWishList" name="testAddToWishList" time="10.249">
    <failure type="java.lang.AssertionError" message="Test failed due to unexpected exception.">
      <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at testCases.TC05_AddToWishList.testAddToWishList(TC05_AddToWishList.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testAddToWishList -->
  <testcase classname="testCases.TC06_AddAffiliate" name="testAddAffiliate" time="5.001"/>
  <testcase classname="testCases.TC02_Login" name="testLogin" time="1.891"/>
  <testcase classname="testCases.TC02_Login" name="testLogin" time="1.638"/>
  <testcase classname="testCases.TC02_Login" name="testLogin" time="1.577"/>
  <testcase classname="testCases.TC02_Login" name="testLogin" time="1.382"/>
  <testcase classname="testCases.TC02_Login" name="testLogin" time="1.927"/>
  <testcase classname="testCases.TC04_CompletePurchase" name="testCompletePurchase" time="1.457">
    <skipped/>
  </testcase> <!-- testCompletePurchase -->
  <testcase classname="testCases.TC04_CompletePurchase" name="testCompletePurchase" time="0.084">
    <skipped/>
  </testcase> <!-- testCompletePurchase -->
  <testcase classname="testCases.TC04_CompletePurchase" name="testCompletePurchase" time="0.069">
    <failure type="java.lang.AssertionError" message="Test failed due to unexpected exception.">
      <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at testCases.TC04_CompletePurchase.testCompletePurchase(TC04_CompletePurchase.java:81)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testCompletePurchase -->
</testsuite> <!-- firefoxTest -->
